services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - rocketlane-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rocketlane-network

networks:
  rocketlane-network:
    driver: bridge
