version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=/app/config/settings.json
    volumes:
      - ./backend/app:/app/backend/app
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - rocketlane-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rocketlane-network

networks:
  rocketlane-network:
    driver: bridge

volumes:
  app-data:
