version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - CONFIG_PATH=/workspace/config/settings.json
    volumes:
      - .:/workspace:cached
      - backend-venv:/workspace/backend/.venv
      - ./config:/workspace/config
    restart: unless-stopped
    networks:
      - rocketlane-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      - ./frontend/index.html:/app/index.html:cached
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rocketlane-network

networks:
  rocketlane-network:
    driver: bridge

volumes:
  backend-venv:
  app-data:
